//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WolfPaw_ScreenSnip.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.3.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool s_hasBgColor {
            get {
                return ((bool)(this["s_hasBgColor"]));
            }
            set {
                this["s_hasBgColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color s_bgColor {
            get {
                return ((global::System.Drawing.Color)(this["s_bgColor"]));
            }
            set {
                this["s_bgColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool s_hasBorder {
            get {
                return ((bool)(this["s_hasBorder"]));
            }
            set {
                this["s_hasBorder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int s_borderWidth {
            get {
                return ((int)(this["s_borderWidth"]));
            }
            set {
                this["s_borderWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color s_borderColor {
            get {
                return ((global::System.Drawing.Color)(this["s_borderColor"]));
            }
            set {
                this["s_borderColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color s_drawColor {
            get {
                return ((global::System.Drawing.Color)(this["s_drawColor"]));
            }
            set {
                this["s_drawColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Arial, 14.25pt")]
        public global::System.Drawing.Font s_font {
            get {
                return ((global::System.Drawing.Font)(this["s_font"]));
            }
            set {
                this["s_font"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color s_textColor {
            get {
                return ((global::System.Drawing.Color)(this["s_textColor"]));
            }
            set {
                this["s_textColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int s_lastTool {
            get {
                return ((int)(this["s_lastTool"]));
            }
            set {
                this["s_lastTool"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string s_lastSaveDir {
            get {
                return ((string)(this["s_lastSaveDir"]));
            }
            set {
                this["s_lastSaveDir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool s_hasDelay {
            get {
                return ((bool)(this["s_hasDelay"]));
            }
            set {
                this["s_hasDelay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3000")]
        public int s_delayLength {
            get {
                return ((int)(this["s_delayLength"]));
            }
            set {
                this["s_delayLength"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int s_lastSaveFormat {
            get {
                return ((int)(this["s_lastSaveFormat"]));
            }
            set {
                this["s_lastSaveFormat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int s_g_SmoothingMode {
            get {
                return ((int)(this["s_g_SmoothingMode"]));
            }
            set {
                this["s_g_SmoothingMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int s_g_InterpolationMode {
            get {
                return ((int)(this["s_g_InterpolationMode"]));
            }
            set {
                this["s_g_InterpolationMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int s_g_PixelOffsetMode {
            get {
                return ((int)(this["s_g_PixelOffsetMode"]));
            }
            set {
                this["s_g_PixelOffsetMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string s_BACKCOLOR {
            get {
                return ((string)(this["s_BACKCOLOR"]));
            }
            set {
                this["s_BACKCOLOR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool s_SaveHasDateTime {
            get {
                return ((bool)(this["s_SaveHasDateTime"]));
            }
            set {
                this["s_SaveHasDateTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public int s_BaseDelay {
            get {
                return ((int)(this["s_BaseDelay"]));
            }
            set {
                this["s_BaseDelay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int s_Delay {
            get {
                return ((int)(this["s_Delay"]));
            }
            set {
                this["s_Delay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool s_HighHandle {
            get {
                return ((bool)(this["s_HighHandle"]));
            }
            set {
                this["s_HighHandle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool s_ClearRequireAuth {
            get {
                return ((bool)(this["s_ClearRequireAuth"]));
            }
            set {
                this["s_ClearRequireAuth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool s_UseCleanButtons {
            get {
                return ((bool)(this["s_UseCleanButtons"]));
            }
            set {
                this["s_UseCleanButtons"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("%this%\\db.sqlite")]
        public string s_DBFileLocation {
            get {
                return ((string)(this["s_DBFileLocation"]));
            }
            set {
                this["s_DBFileLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40")]
        public int s_ButtonSize {
            get {
                return ((int)(this["s_ButtonSize"]));
            }
            set {
                this["s_ButtonSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int s_HandleSize {
            get {
                return ((int)(this["s_HandleSize"]));
            }
            set {
                this["s_HandleSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int s_ToolbarPanel {
            get {
                return ((int)(this["s_ToolbarPanel"]));
            }
            set {
                this["s_ToolbarPanel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool s_handlePrintScreen {
            get {
                return ((bool)(this["s_handlePrintScreen"]));
            }
            set {
                this["s_handlePrintScreen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool s_MoveToTools {
            get {
                return ((bool)(this["s_MoveToTools"]));
            }
            set {
                this["s_MoveToTools"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.5")]
        public float s_CanvasTransparency {
            get {
                return ((float)(this["s_CanvasTransparency"]));
            }
            set {
                this["s_CanvasTransparency"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Silver")]
        public global::System.Drawing.Color s_CanvasColor {
            get {
                return ((global::System.Drawing.Color)(this["s_CanvasColor"]));
            }
            set {
                this["s_CanvasColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool s_RememberLastPosition {
            get {
                return ((bool)(this["s_RememberLastPosition"]));
            }
            set {
                this["s_RememberLastPosition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point s_LastPosition {
            get {
                return ((global::System.Drawing.Point)(this["s_LastPosition"]));
            }
            set {
                this["s_LastPosition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int s_LastUsedMode {
            get {
                return ((int)(this["s_LastUsedMode"]));
            }
            set {
                this["s_LastUsedMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool s_HandleShortcuts {
            get {
                return ((bool)(this["s_HandleShortcuts"]));
            }
            set {
                this["s_HandleShortcuts"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Gainsboro")]
        public global::System.Drawing.Color s_ScreenBGColor {
            get {
                return ((global::System.Drawing.Color)(this["s_ScreenBGColor"]));
            }
            set {
                this["s_ScreenBGColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ActiveCaption")]
        public global::System.Drawing.Color s_CutoutPanelColor {
            get {
                return ((global::System.Drawing.Color)(this["s_CutoutPanelColor"]));
            }
            set {
                this["s_CutoutPanelColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color s_CutoutSelectionColor {
            get {
                return ((global::System.Drawing.Color)(this["s_CutoutSelectionColor"]));
            }
            set {
                this["s_CutoutSelectionColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("180, 180, 180")]
        public global::System.Drawing.Color s_CutoutMouseOverColor {
            get {
                return ((global::System.Drawing.Color)(this["s_CutoutMouseOverColor"]));
            }
            set {
                this["s_CutoutMouseOverColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool s_ShowPreview {
            get {
                return ((bool)(this["s_ShowPreview"]));
            }
            set {
                this["s_ShowPreview"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int s_LastPreviewMode {
            get {
                return ((int)(this["s_LastPreviewMode"]));
            }
            set {
                this["s_LastPreviewMode"] = value;
            }
        }
    }
}
